steps:
  # Step 1: Use a Node.js image to install dependencies
  - name: 'node:18'
    id: 'Install Dependencies'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Install Playwright browsers
  - name: 'node:18'
    id: 'Install Playwright Browsers'
    entrypoint: 'npx'
    args: ['playwright', 'install', '--with-deps']

  # Step 3: Run Playwright tests
  - name: 'node:18'
    id: 'Run Playwright Tests'
    entrypoint: 'npx'
    args: ['playwright', 'test']

  # Step 4 (Optional): Upload test results to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Upload Test Results'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m cp -r test-results/* gs://$PROJECT_ID-playwright-results/
options:
  logging: CLOUD_LOGGING_ONLY

timeout: 6000s
