steps:
  - name: 'gcr.io/cloud-builders/python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pytest --junitxml=report.xml
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'report.xml', 'gs://YOUR_BUCKET/reports/report.xml']
options:
  logging: CLOUD_LOGGING_ONLY
