steps:
  - name: 'mcr.microsoft.com/playwright:v1.41.1-jammy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npx playwright install --with-deps
        npx playwright test

  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m cp -r playwright-report/index.html gs://portfolio-bucke/index.html
        

options:
  logging: GCS_ONLY
logsBucket: gs://portfolio-bucke
