steps:
  - name: 'node'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm playwright test

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'report.xml', 'gs://portfolio-bucke/reports/report.xml']

options:
  logging: GCS_ONLY
logsBucket: gs://portfolio-bucke