steps:
  - name: 'mcr.microsoft.com/playwright:v1.41.1-jammy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'report.xml', 'gs://portfolio-bucke/reports/report.xml']

options:
  logging: GCS_ONLY
logsBucket: gs://portfolio-bucke